name: target_medical
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.1
  recase: ^4.1.0
  flutter_svg: ^2.0.6
  http: ^0.13.6
  connectivity_plus: ^4.0.1
  get: ^4.6.5
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  syncfusion_flutter_sliders: ^20.4.53
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1
  mobile_device_identifier: ^0.0.2
  pie_chart: ^5.3.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  marquee: ^2.2.3
  video_player: ^2.6.1
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2
  flutter_launcher_icons: ^0.13.1
  otp_text_field: ^1.1.3
  url_launcher: ^6.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/anim/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/sounds/
    - assets/videos/

  fonts:

    - family: LiAdorNoirritSemiBold
      fonts:
        - asset: assets/fonts/Li_Ador_Noirrit_SemiBold.ttf

    - family: LiAdorNoirritRegular
      fonts:
        - asset: assets/fonts/Li_Ador_Noirrit_Regular.ttf

    - family: LiAdorNoirritBold
      fonts:
        - asset: assets/fonts/Li_Ador_Noirrit_Bold.ttf

